version: '3.9'

services:
  api:
    build: ./
    command: yarn dev
    working_dir: /usr/src/app
    environment:
      - POSTGRES_URI=postgres://postgres:postgres@postgres:5432/teenageconcerns
      - NODE_ENV=production
      - REDIS_URI=redis://redis:6379
    ports:
      - 5000:5000
    depends_on:
      - postgres
      - redis
  
  postgres:
    image: postgres:14.4
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    volumes:
      - ./postgres/init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
    
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    hostname: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
  
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf/:/etc/nginx/nginx.conf