name: BUILD & DOCKERIZE

on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
        #Checks out the repo 
      - name: Check Out Repo 
        uses: actions/checkout@v2

        #Logs into Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

        #Uses buildx buildkit runner
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

        #Builds and pushes the image onto github
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/teenageconcerns-graphql:latest

      - name: Image digest
        run: echo ${{ steps }}